### ISSUE TITLE
Authentication Error: Check if your login credentials are correct. Receive response code: 403 Forbidden

### ISSUE THREAD

**Issue by AFI4711** [floek/wemportal#8]
Hi, 
since some weeks, I get the following error more and more often:

`Traceback (most recent call last):
  File "/home/andi/haus/wemportal-floek/wemportal-main/wemportal_api.py", line 13, in <module>
    api.login()
  File "/home/andi/haus/wemportal-floek/wemportal-main/wemportal/wem_portal.py", line 22, in login
    self.__web.login()
  File "/home/andi/haus/wemportal-floek/wemportal-main/wemportal/wem_portal_web.py", line 45, in login
    raise WemPortalConnectionError(
wemportal.exceptions.WemPortalConnectionError: Authentication Error: Check if your login credentials are correct. Receive response code: 403, response: b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>Microsoft-Azure-Application-Gateway/v2</center>\r\n</body>\r\n</html>\r\n'
`
The login on https://www.wemportal.com/Web/Login.aspx works fine.
Otherwise the API works great!

**Comment by AFI4711** [comment]
**Since yesterday evening the error messages changes**, when running wemportal_api.py:

```
Traceback (most recent call last):
  File "/home/andi/Computer/src/wemportal/wemportal-floek/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andi/Computer/src/wemportal/wemportal-floek/wemportal-main/wemportal_api.py", line 14, in <module>
    devices = api.fetch_devices()
  File "/home/andi/Computer/src/wemportal/wemportal-floek/wemportal-main/wemportal/wem_portal.py", line 26, in fetch_devices
    devices = self.__api.fetch()
  File "/home/andi/Computer/src/wemportal/wemportal-floek/wemportal-main/wemportal/wem_portal_api.py", line 60, in fetch
    self.get_devices()
  File "/home/andi/Computer/src/wemportal/wemportal-floek/wemportal-main/wemportal/wem_portal_api.py", line 89, in get_devices
    module.parameters = [WemParameterParser.load(param) for param in response.json()["Parameters"]]
  File "/home/andi/Computer/src/wemportal/wemportal-floek/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Do you know what is going wrong?

**Comment by floek** [comment]
Hi, I'm getting similar errors. Maybe weishaupt is blocking the requests. Needs investigation .....

**Comment by AFI4711** [comment]
Hi, the Weishaupt WEM Portal shows some problems currently:
![image](https://github.com/user-attachments/assets/28c88f06-b43c-4698-9dcc-c4cddd08aed0)
Perhaps we should wait ...

**Comment by AFI4711** [comment]
system is working fine since 2024-11-18 14:00.
